0.6.0
ShunkevichDV/sc-machine pull request #21
Opened 2020-08-05 10:27 UTC by Zioba

* [ ] Read PR [documentation](http://ostis-dev.github.io/sc-machine/dev/pr/)
* [ ] Update changelog
* [ ] Update documentation

2020-08-06 14:47 UTC, Zioba commented
1) implement concertedKB feature
2) update parser for ims KB integration
3) implement generation KB dump

2020-08-07 13:00 UTC, KovalM requested changes

2020-08-07 13:00 UTC, KovalM commented on sc-kpm/scp/scp_keynodes.c
> +    if (sc_helper_resolve_system_identifier(s_default_ctx, "concertedKB_hash_iF95K2", &(concertedKb)) == SC_FALSE) { \
Move to constants

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-core/sc_helper.c
> +sc_result sc_helper_set_system_identifier_new(sc_memory_context const * ctx, sc_addr addr, const sc_char* data, sc_uint32 len, sc_addr rootEl, sc_bool isAddRoot)
Why we need _new suffix? What is rootEl(rename)?

Why we need isAddRoot flag?
We can just add to rootEl if rootEl not null

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-core/sc_helper.c
> +    if (isAddRoot) {
Move { to next line. Apply it to all your code

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-memory/sc_link.hpp
> +        ScAddr x = m_ctx.CreateEdge(ScType::EdgeAccessConstPosTemp, newType, m_addr);
Rename x

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-memory/sc_scs_helper.cpp
> +//        if (src.GetType().IsEdge() | trg.GetType().IsEdge()) {
Remove not used code

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-memory/sc_memory.cpp
> +        ScAddr sysId = HelperFindBySystemIdtf("nrel_system_identifier");
Use SC_KEYNODE_NREL_SYSTEM_IDENTIFIER

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-memory/sc_memory.cpp
> +        ScAddr sysId = HelperFindBySystemIdtf("nrel_system_identifier");
sysId and sysIdtf have the same semantic. Rename sysId to sysIdtfRelation

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-memory/sc_scs_helper.cpp
> +      if (!edge.GetType().IsEdge()) {
Move { to the next line

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-memory/sc_scs_helper.cpp
> +            ScAddr sysId = m_ctx.HelperFindBySystemIdtf("nrel_system_identifier");
Use SC_KEYNODE_NREL_SYSTEM_IDENTIFIER

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-memory/sc_scs_helper.cpp
> +            ScAddr sysId = m_ctx.HelperFindBySystemIdtf("nrel_system_identifier");
I already seen this code in sc_memory.cpp. Did you try don't make duplicate?

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-memory/sc_scs_helper.cpp
> +  std::string concertedKBName = "concertedKB_hash_iF95K2";
Make it constants(static, caps name). Move to special constants class because you need to share it

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-memory/sc_scs_helper.hpp
> +};
Remove this Github warning

2020-08-07 13:00 UTC, KovalM commented on sc-memory/sc-memory/sc_template_gen.cpp
> +      ScAddr concertedKB = m_context.HelperFindBySystemIdtf("concertedKB_hash_iF95K2");
HelperFindBySystemIdtf is expensive operation. Try to do it one time and share found sc addr

2020-08-12 08:26 UTC, Zioba commented on sc-memory/sc-memory/sc_memory.cpp
> +        ScAddr sysId = HelperFindBySystemIdtf("nrel_system_identifier");
Don't compile

2020-08-12 08:44 UTC, Zioba commented on sc-memory/sc-core/sc_helper.c
> +sc_result sc_helper_set_system_identifier_new(sc_memory_context const * ctx, sc_addr addr, const sc_char* data, sc_uint32 len, sc_addr rootEl, sc_bool isAddRoot)
We have disscussed it in the same situation for scp_stable_context. We need this method to not to break compatibility. see comment on sc-memory/sc-core/sc_helper.h line 33

2020-08-12 08:55 UTC, Zioba commented on sc-memory/sc-memory/sc_template_gen.cpp
> +      ScAddr concertedKB = m_context.HelperFindBySystemIdtf("concertedKB_hash_iF95K2");
Builder system in 0.6.0 version is decentralized system, which generate new pool of instances for every .scs file during building KB. That is why we need to initialize concertedKB every time.

2020-08-13 16:39 UTC, merged